.github/workflows/trunk.yml
I get an error when using the latest:
```
[commonjs--resolver] Failed to resolve entry for package "@agoric/ui-components". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@agoric/ui-components". The package may have incorrect main/module/exports specified in its package.json.
```
I think because the package was missing its `dist` folder, because it isn't being built before being published. @turadg I may need help testing this
=> build: build ui-components before publishing

packages/web-components/src/wallet-connection/watchWallet.js
refs https://github.com/Agoric/dapp-inter/issues/151
`res()` was never being called because the data was empty, and the callback was returning early. So, the wallet connection was hanging forever.
The empty wallet data state resulted from a smart wallet that was created before the vaults upgrade, but had never made an offer.
We'll need to update the dapps after this new version is published.
=> fix: resolve wallet connection for empty wallet data

packages/rpc/package.json, packages/rpc/tsconfig.build.json, packages/rpc/tsconfig.json, packages/web-components/package.json, packages/web-components/tsconfig.build.json
The `dist` path wasn't being included in builds.
=> build: prepack

packages/rpc/CHANGELOG.md, packages/rpc/package.json, packages/ui-components/CHANGELOG.md, packages/ui-components/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
- @agoric/rpc@0.5.0
- @agoric/ui-components@0.8.0
- @agoric/web-components@0.11.0
=> chore(release): publish

packages/web-components/index.js, packages/web-components/src/wallet-connection/suggestChain.js
fixes https://github.com/Agoric/ui-kit/issues/32
=> feat: suggest chain

packages/web-components/src/wallet-connection/makeInteractiveSigner.js, packages/web-components/src/wallet-connection/walletConnection.js, packages/web-components/src/wallet-connection/watchWallet.js, packages/web-components/test/walletConnection.test.js
closes: #41 
Updates to the [interactiveSigner](https://github.com/WietzeSlagman/ui-kit/blob/main/packages/web-components/src/wallet-connection/makeInteractiveSigner.js) which includes a `submitProvision` transaction that provisions a smart wallet for the account provided to `makeAgoricWalletConnection`.
Updates to [walletConnection](https://github.com/WietzeSlagman/ui-kit/blob/main/packages/web-components/src/wallet-connection/walletConnection.js) exposing the `submitProvision` to the dev through `makeAgoricWalletConnection`
Updates to [watchWallet](https://github.com/WietzeSlagman/ui-kit/blob/main/packages/web-components/src/wallet-connection/watchWallet.js) no longer throwing on an account that doesn't have a smart-wallet attached to it. This is something to potentially update and …
=> smart-wallet provisioning from web-components

packages/rpc/src/batchQuery.ts, packages/rpc/src/chainStorageWatcher.ts, packages/rpc/test/chainStorageWatcher.test.ts, packages/web-components/src/wallet-connection/walletConnection.js, packages/web-components/src/wallet-connection/watchWallet.js, packages/web-components/test/walletConnection.test.js
refs: https://github.com/Agoric/ui-kit/issues/53
For the chain storage watcher, no longer use the deprecated RPC method to query vstorage. Instead, use the JSON API. There's a lot of ways to handle the query logic, but for now this just keeps the same internal logic and makes a shotgun of requests instead of a batch query. Bandwidth consumption seems roughly similar after increasing the polling period a bit, and the increased request count should have minimal impact with [connection coalescing](https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/).
Also, updates the wallet connection component because it was relying on the watcher having an RPC node.
Updated unit tests and validated with https://github.com/Agoric/dapp-inter/pull/209 locally using yarn link
=> Update deprecated vstorage queries

packages/rpc/src/batchQuery.ts, packages/rpc/src/chainStorageWatcher.ts, packages/rpc/test/chainStorageWatcher.test.ts, packages/web-components/src/wallet-connection/watchWallet.js
fixes https://github.com/Agoric/ui-kit/issues/58
=> fix: dont throw on missing smart wallet

packages/web-components/package.json, packages/web-components/src/wallet-connection/walletConnection.js, packages/web-components/src/wallet-connection/watchWallet.js, yarn.lock
refs https://github.com/Agoric/ui-kit/issues/57
Tested in a local build of dapp-inter that this fixes the issue. Will close the issue when this is published and dapp-inter and dapp-psm use the new version.
Screenshot of error properly being shown to user after fix:
=> fix(web-components): handle failed offer status updates better

packages/web-components/src/wallet-connection/queryBankBalances.js, packages/web-components/src/wallet-connection/walletConnection.js, packages/web-components/src/wallet-connection/watchWallet.js
refs https://github.com/Agoric/agoric-sdk/issues/8505
We improved error handling to the `chainStorageWatcher` in https://github.com/Agoric/ui-kit/pull/65, but the `makeAgoricWalletConnection` component uses the RPC endpoint rather than the API endpoint, and doesn't surface errors conveniently when queries fail. This adds an `onRpcError` parameter so that clients can respond accordingly when the RPC node is failing.
Also, made it only call `await Tendermint34Client.connect(rpc)` once instead of every time it queries the bank. This removes an [extra round trip](https://github.com/cosmos/cosmjs/blob/97a54b8a101263b75faceadcd0462a2f3f265103/packages/tendermint-rpc/src/tendermint34/tendermint34client.ts#L42) to reduce load on the RPC node. Also added up to 2 retries around `queryBank` because …
=> feat(web-components): surface wallet connection rpc errors

packages/rpc/CHANGELOG.md, packages/rpc/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
Before publishing a new release, this will sync the current version to what was most recently published from https://github.com/Agoric/ui-kit/commit/d174be74cac2fffaf47dc9c0e603744a57ef3e5c
=> chore: sync release version with upgrade-12-stable branch

packages/rpc/src/chainStorageWatcher.ts, packages/web-components/src/wallet-connection/watchWallet.js
The provision status for non-provisioned accounts was coming back as `provisioned: false` initially, but the next time it polled the status, it would treat the empty string value `""` as a new value because it was comparing it to the `JSON.stringify` result of `'""'` which is different. This was a bug in `@agoric/rpc` because of the redundant update, which also exposed a bug in `@agoric/web-components` because it was always reporting the status as `provisioned: true` for subsequent updates, no matter what the value was. Fixed both.
=> Fix provision status bug

packages/web-components/package.json, yarn.lock
For some reason now when testing dapp-inter with the new [version](https://www.npmjs.com/package/@agoric/web-components/v/0.14.1-dev-9cde92b.0) of `web-components`, I'm seeing https://github.com/Agoric/agoric-sdk/issues/8601 manifest. When a user visits with no smart wallet, then provisions, then creates a vault, the offer status doesn't come through. I tested locally with yarn link to validate that this fixes the issue, but will need to test again with the npm published package to validate that there's no weirdness with yarn link misleading me. However, the package should be updated regardless.
=> fix(web-components): update casting

packages/rpc/package.json, packages/rpc/src/marshal.ts, packages/rpc/test/marshal.test.ts, yarn.lock
include slot (usually boardID) in label of synthetic remotables
for example: `[object Alleged: Brand#board0123]` instead of just `[object Alleged: Brand]`
Some similar things can only be done for debugging because otherwise they divulge info to parties that shouldn't have it.
But I believe it's OK in this context even in production: the client already knows the boardID.
n/a
I expect this to enhance clarity in some situations. (I hope to contribute something similar to the vstorage viewer.)
I don't consider these labels to be part of the API, so I do **not** consider this a breaking change.
I'm not aware of any clients that depend on the string form of these labels. Feedback from reviewers on this is particularly welcome, in any case.
one straightforward unit test is included. seems …
=> feat: include slot in synthesized remotable label

packages/rpc/src/chainStorageWatcher.ts
closes: #XXXX
refs: #47
Replaces `window.(set|clear)Timeout()` with `globalThis.(set|clear)Timeout()` so this export can be used in Node.js.
This change might involve ambient authority (globalThis), but this authority was already present in the original implementation.
N/A
When #47 is closed, we should update docs to explain Node.js support. 
Existing tests should cover these changes.
=> feat(chainStorageWatcher): enable non-browser compatability

packages/rpc/index.ts, packages/rpc/src/chainStorageWatcher.ts, packages/rpc/src/vstorageQuery.ts, packages/rpc/test/chainStorageWatcher.test.ts, packages/rpc/vitest.config.ts, packages/web-components/src/dapp-wallet-bridge/DappWalletBridge.js
@0xpatrickdev ran into,
```
Error: Cannot find module '/Users/0xpatrick/repos/dapp-offer-up/node_modules/@agoric/rpc/dist/src/chainStorageWatcher' imported from /Users/0xpatrick/repos/dapp-offer-up/node_modules/@agoric/rpc/dist/index.js
```
and suggested the packages shoudl be compatible with ESM.  I think this PR fixes that, though I don't know a good way to include a regression test.
=> fix ESM compat

packages/rpc/package.json, yarn.lock
We need to use `.js` when importing local typescript files for ESM compatibility. https://github.com/Agoric/ui-kit/pull/76 fixes this, but this PR adds an eslint plugin (thanks [solana](https://github.com/solana-labs/eslint-plugin-require-extensions)) to protect against breaking it again.
I looked into other options, like libraries that transform extensionless imports to `.js` automatically, but seems like `.js` extensions are a common pattern in typescript libraries, and it seems less risky to not muck around with the build process.
Example output:
=> ci: require js extensions on local imports

packages/web-components/src/wallet-connection/watchWallet.js
We changed it recently to wrap the marshaller in `Far`, which resulted in the following error and offer updates not being received:
```
wallet connection error Error: RPC error - Error: Remotable {"fromCapData":"[Function mn]","serialize":"[Function Ft]","toCapData":"[Function Ft]","unserialize":"[Function mn]"} is already frozen
```
=> fix: avoid marshaller error in watchWallet

packages/react-components/README.md, packages/react-components/src/lib/components/NetworkDropdown.tsx, packages/react-components/src/lib/components/NodeSelectorModal.tsx, packages/react-components/src/lib/components/index.ts, packages/react-components/src/lib/config/index.ts, packages/react-components/src/lib/context/NetworkContext.tsx, packages/react-components/src/lib/hooks/index.ts, packages/react-components/src/lib/hooks/network.ts
fixes: https://github.com/Agoric/agoric-sdk/issues/8933
Tested locally with https://github.com/Agoric/dapp-offer-up/commit/b73b8c0dc4fd6002765082108807e942f86023a5
=> Network Dropdown

package.json, packages/react-components/package.json
fixes #100
punt on an engines constraint
can't think of any
not sure; is some documentation in order?
I presume this doesn't need testing. Reviewers, please chime in.
=> chore: omit engines constraint

.github/workflows/ci.yml, .gitignore, package.json, packages/react-components/package.json, packages/rpc/package.json, packages/rpc/typedoc.json, packages/web-components/typedoc.json, typedoc.base.json, typedoc.json, yarn.lock
refs:
- https://github.com/Agoric/documentation/issues/1047
Generate api-doc using typedoc.
adds typedoc to devDependencies
n/a
It would be nice if we had examples that get tested. But I suppose we're not there yet.
=> generate api docs with typedoc

packages/react-components/src/lib/context/AgoricContext.ts, packages/react-components/src/lib/context/AgoricProviderLite.tsx, packages/web-components/package.json, packages/web-components/src/wallet-connection/querySwingsetParams.js, packages/web-components/src/wallet-connection/walletConnection.js, packages/web-components/src/wallet-connection/watchWallet.js, yarn.lock
refs https://github.com/Agoric/ui-kit/issues/78
This queries the smart wallet auto-provision fee in the wallet connection component, and exposes it in the react `useAgoric` hook as well.
Also fixed a bug where the purse notifier was updating every time the bank was polled, even if the balances didn't change. (cc @0xpatrickdev)
Tested on this branch of dapp-offer-up: https://github.com/Agoric/dapp-offer-up/compare/test-network-dropdown
Steps:
- Build ui-kit with `yarn && yarn workspaces run prepack`
- Set up link with `cd packages/react-components && yarn link`
- Clone `dapp-offer-up` and checkout this branch: https://github.com/Agoric/dapp-offer-up/compare/test-network-dropdown
- Start the local chain with docker (the offer-up contract doesn't necessarily have to be deployed to test this …
=> feat: query smart wallet auto-provision fee

packages/react-components/README.md, packages/react-components/src/lib/components/NetworkDropdown.tsx, packages/react-components/src/lib/context/AgoricProvider.tsx, packages/react-components/src/lib/context/NetworkContext.tsx, packages/react-components/src/lib/context/NetworkProvider.tsx
fixes https://github.com/Agoric/ui-kit/issues/96
Removes the `defaultNetworkConfig` prop from `AgoricProvider` in favor of:
- `agoricNetworkConfigs` for specifying the available networks.
- And, `defaultChainName` for selecting the default network. 
Now, instead of passing in `networkConfigs` to the network dropdown component, it just reads from `agoricNetworkConfigs`.
Built successfully and linked locally with dapp-offer-up, tested the new API and switching between multiple networks.
=> feat(react-components)!: rework network dropdown and network config

package.json
refs: #8273
This repo is already using the Ava default glob so this PR just removes the vestige that was selecting the old one
=> test: rely on Ava default glob

packages/react-components/src/lib/context/AgoricProviderLite.tsx
refs https://github.com/Agoric/dapp-orchestration-basics/issues/43
This way we'll be able to use `walletConnection.signingClient` to send an IBC transfer instead of [creating our own signer](https://github.com/Agoric/dapp-orchestration-basics/blob/f7a4ed386582f7f6b00d7f997ae8d79b1c05c3c2/ui/src/components/Orchestration/Orchestration.tsx#L160-L166) which doesn't use the wallet extension and rpc endpoints configured by cosmos-kit.
Tested locally with dapp-orchestration-basics https://github.com/Agoric/dapp-orchestration-basics/commit/ca700b2971181f971a329ee73bb56a8ba7a7b210
=> feat(react-components): support IBC messages in signer

package.json, packages/example/src/components/WalletDetails.tsx, packages/react-components/package.json, packages/web-components/package.json, packages/web-components/src/wallet-connection/makeAgoricSigner.ts, packages/web-components/src/wallet-connection/queryBankBalances.ts, packages/web-components/src/wallet-connection/querySwingsetParams.js, packages/web-components/src/wallet-connection/signerOptions.ts, packages/web-components/tsconfig.json, yarn.lock
refs: https://github.com/agoric-labs/ymax-poc-ui/issues/58
Updating cosmjs seems to fix the issue. I used resolutions to ensure the latest cosmjs is used because there's some deps that I couldn't untangle importing older cosmjs still.
Tested first in packages/example, then in https://github.com/agoric-labs/ymax-poc-ui/pull/75 after publishing dev releases for the packages.
Also makes the default fee non-zero to try and ensure it doesn't present an approval with zero BLD fees (I noticed this issue during @dckc's demo, but was unable to repro this issue on a fresh keplr install myself)
=> fix: use latest compatible cosmjs
